#%RAML 1.0
title: Azure DevOps API

/azure:
  get:
    responses:
      200:
        body:
          application/json:
            example: |
              [ 
                {"name": "Employees Exp API"},
                {"name": "HR Process API"}
              ]